spring:
  kafka:
    bootstrap-servers: localhost:29092

its:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5433/ITS
    username: postgres
    password: postgres