server:
  port: 8081
  servlet:
    session:
      cookie:
        same-site: lax

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/its-realm

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: ${eureka_url:http://localhost:8080/eureka}
  instance:
    hostname: localhost
    prefer-ip-address: true