server:
  port: 8081
  servlet:
    session:
      cookie:
        same-site: lax
  forward-headers-strategy: native

logging:
  level:
    org.springframework.security: DEBUG

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8090/realms/its-realm}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8080/eureka}
  instance:
    hostname: gateway-service
    prefer-ip-address: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /api/its/v3/api-docs
        name: Issue Tracking Service

swagger:
  url: "http://localhost:${server.port}"
