server:
  port: 9001
  servlet:
    context-path: /api/its

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/its
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        format_sql: false
        show_sql: false
    database: postgresql
  application:
    name: issue-tracking-service
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:29092}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8080/eureka}
  instance:
    hostname: issue-tracking-service
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}