server:
  port: 9001
  servlet:
    context-path: /api/its

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ITS
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        format_sql: false
        show_sql: false
  application:
    name: issue-tracking-service
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: ${eureka_url:http://localhost:8080/eureka}
  instance:
    hostname: localhost
    prefer-ip-address: true